package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.HallMenu;
import org.linlinjava.litemall.db.domain.HallMenuExample;

public interface HallMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    long countByExample(HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int deleteByExample(HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int insert(HallMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int insertSelective(HallMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    HallMenu selectOneByExample(HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    HallMenu selectOneByExampleSelective(@Param("example") HallMenuExample example, @Param("selective") HallMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    List<HallMenu> selectByExampleSelective(@Param("example") HallMenuExample example, @Param("selective") HallMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    List<HallMenu> selectByExample(HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    HallMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") HallMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    HallMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HallMenu record, @Param("example") HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HallMenu record, @Param("example") HallMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HallMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HallMenu record);
}